name: Sonar Test

on: 
  workflow_dispatch:
jobs:
  SonarCloud:
    name: Sonar Cloud
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Sonar Cloud Test
      uses: SonarSource/sonarcloud-github-action@master
      env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    
    
